####### Target and machine specific flags for compilation and linking #######

# Location of the charm installation
CHARMBASE	= $(HOME)/charm

# Location of the FFTW library installation
FFT_HOME	= $(HOME)/fftw

# Should we use dual fft or not
DUAL_FFTW	= -DDUAL_FFTW_OFF

# Special options to used for compiling fastadd.C
MATH_OPTS	=

# Extra preprocessor flag to be used just for ibm_essl_dummy.o
IBM_ESSL_DUMMY	=

# Blas/ Lapack/ Eispack sources that need to be compiled
src_math    = $(src_blas) $(src_lapack) $(src_eispack)

# Extra math libraries to be linked in
MATH_LIB	=

# Other libraries that need to be linked in
LDLIBS     += -lm

# Where should we look for standard_include.h
STANDARD_INC= $(physics)/include/pentium_par

# Other target specific flags
$(libphysics): OPT_CARE   = -O2
$(libphysics): FFLAGS    += -fno-second-underscore

