#!/bin/sh

if [ ! -d STATES_OUT ] ; then
mkdir STATES_OUT
fi

cd STATES_OUT
(cd ../STATES; find -type d ! -name .) | xargs mkdir
cd ..

if [ ! -d ATOM_COORDS_OUT ] ; then
mkdir ATOM_COORDS_OUT
cd ATOM_COORDS_OUT
(cd ../ATOM_COORDS_IN; find -type d ! -name .) | xargs mkdir
cd ..
fi

if [ ! -d TEMPER_OUT ] ; then
mkdir TEMPER_OUT
mkdir TEMPER_OUT/Temper.0
fi
