CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C ROUTINE TO MULTIPLY X*Y = Z C WITH OPTIONAL TRANSPOSES ON X AND/OR Y
C
      SUBROUTINE genmatmul(X,LDX,ITYP_X,Y,LDY,ITYP_Y,Z,LDZ,
     #                      NRZ,NCZ,NXY,ALPHA,BETA)
C (double *, ok, int *, double *, int *, int *, double *, int *, int *, int *, int *, double *, double *)
      IMPLICIT NONE
C LEADING DIMENSIONS OF X,Y,Z
      INTEGER LDX,LDY,LDZ
C THE MATRICES X,Y,Z
      REAL*8 X(LDX,*), Y(LDY,*),Z(LDZ,*)
C NUMBER OF ROWS IN ANSWER MATRIX Z
C NUMBER OF COLS IN ANSWER MATRIX Z
C NUMBER OF ELEMETNS YOU ARE SUMMING OVER IN X AND Y
      INTEGER NRZ,NCZ,NXY
C TRANSPOSE OPTIONS
      INTEGER ITYP_X,ITYP_Y
      CHARACTER MATX,MATY
c LOCAL VARIABLES
      REAL*8 ALPHA,BETA
C HP_MATRIX MULTIPLY ROUTINE
C X TYPE
      MATX = 'N'
      IF(ITYP_X .EQ. 0)THEN
        MATX(1:1) = 'T'
      ENDIF
C Y TYPE
      MATY = 'N'
      IF(ITYP_Y .EQ. 0)THEN
        MATY(1:1) = 'T'
      ENDIF
      CALL DGEMM(MATX,MATY,NRZ,NCZ,NXY,ALPHA,X,LDX,Y,LDY,BETA,Z,LDZ)
      RETURN
      END
